"use client";

import { motion } from "framer-motion";
import { Brain, ChartLine, Lightbulb, Shield, Sparkles, Layers, Zap, Atom, Telescope } from "lucide-react";
import { TiltCard, ScanningBeam, HolographicBadge, FloatingOrb } from "./futuristic-effects";

const features = [
  { icon: Brain, title: "Adaptive Intelligence", description: "Questions adapt in real-time using Item Response Theory (IRT) and Bayesian Knowledge Tracing (BKT), extracting maximum diagnostic information from every answer.", gradient: "from-primary-500 to-primary-600" },
  { icon: ChartLine, title: "Deep Analytics", description: "Radar charts, heatmaps, learning curves, and knowledge graphs that reveal exactly what's happening in your child's mind — not just scores.", gradient: "from-secondary-500 to-secondary-600" },
  { icon: Lightbulb, title: "Misconception Detection", description: "We don't just mark answers wrong — we identify exactly which misconception caused the error and trace it to its root source.", gradient: "from-amber-500 to-orange-600" },
  { icon: Shield, title: "Cognitive Skills Analysis", description: "Measure critical thinking, reasoning, problem-solving, and knowledge transfer across Bloom's taxonomy levels.", gradient: "from-emerald-500 to-emerald-600" },
  { icon: Atom, title: "IRT Scoring Engine", description: "3-Parameter Logistic Model (3PL) estimates true ability (theta) with standard error, independent of test difficulty.", gradient: "from-cyan-500 to-cyan-600" },
  { icon: Telescope, title: "Predictive Analytics", description: "Forecast future performance, identify at-risk students early, and generate 4-6 week growth projections with 90%+ confidence.", gradient: "from-violet-500 to-violet-600" },
  { icon: Sparkles, title: "AI Recommendations", description: "Personalized daily, weekly, and monthly plans generated by GPT-4-class models to close every learning gap systematically.", gradient: "from-pink-500 to-rose-600" },
  { icon: Layers, title: "Multi-Stakeholder Insights", description: "Separate dashboards for students, parents, teachers, and school administrators with role-specific intelligence and actionable data.", gradient: "from-indigo-500 to-indigo-600" },
  { icon: Zap, title: "Real-Time Processing", description: "Results in seconds. The engine processes responses, estimates ability, generates reports, and delivers insights instantly after assessment completion.", gradient: "from-yellow-500 to-amber-600" },
];

export function DeepIntelligence() {
  return (
    <section id="features" className="relative overflow-hidden border-y border-white/5 bg-slate-900/30 py-24 lg:py-32">
      {/* Holographic grid background */}
      <div className="data-grid pointer-events-none absolute inset-0 opacity-30" />

      <FloatingOrb color="from-primary-500/10 to-secondary-500/8" size={600} className="top-0 right-0 translate-x-1/3 -translate-y-1/4" blur="blur-[120px]" />
      <FloatingOrb color="from-cyan-500/8 to-primary-500/5" size={500} className="bottom-0 left-0 -translate-x-1/4 translate-y-1/3" blur="blur-[100px]" animation="animate-orb-drift-2" />

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <HolographicBadge text="Deep Intelligence Platform" />
          <h2 className="mt-6 text-4xl font-bold text-white lg:text-5xl">
            Beyond Simple Testing
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-slate-400">
            Deep Check is not another exam platform. It&apos;s a diagnostic intelligence engine powered by cognitive science, IRT, and AI.
          </p>
        </motion.div>

        <div className="mt-16 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: i * 0.06 }}
              viewport={{ once: true }}
              className="group"
            >
              <TiltCard maxTilt={4} glare={true}>
                <div className="relative overflow-hidden rounded-xl border border-white/5 bg-slate-900/60 p-6 backdrop-blur-sm transition-all duration-500 group-hover:border-white/10 group-hover:bg-slate-900/80 holo-card scan-overlay" style={{ minHeight: "220px" }}>
                  <ScanningBeam />

                  <div className="relative flex items-start gap-4">
                    <div className="relative flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary-500/10 to-secondary-500/10 text-primary-400 transition-all duration-500 group-hover:scale-110 group-hover:shadow-lg overflow-hidden">
                      <div className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 transition-opacity duration-500 group-hover:opacity-100`} />
                      <feature.icon className="relative h-6 w-6 transition-colors duration-500 group-hover:text-white" />
                    </div>
                    <div className="min-w-0">
                      <h3 className="text-lg font-semibold text-white transition-colors duration-300 group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-primary-300 group-hover:to-secondary-300">
                        {feature.title}
                      </h3>
                      <p className="mt-2 text-sm leading-relaxed text-slate-400">
                        {feature.description}
                      </p>
                    </div>
                  </div>

                  {/* Bottom accent bar */}
                  <div className={`absolute bottom-0 left-0 right-0 h-[2px] bg-gradient-to-r ${feature.gradient} opacity-0 transition-all duration-500 group-hover:opacity-100`}
                    style={{ boxShadow: `0 0 15px rgba(59,130,246,0.3)` }}
                  />
                </div>
              </TiltCard>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
