export default function TosPage() {
  return (
    <main className="px-4 py-16 sm:py-24">
      <div className="mx-auto max-w-3xl prose prose-neutral dark:prose-invert">
        <h1 className="text-3xl font-extrabold sm:text-5xl text-neutral-900 dark:text-white">Terms of Service</h1>
        <p className="text-neutral-500">Last updated: July 2026</p>

        <section className="mt-8 space-y-4">
          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">1. Acceptance of Terms</h2>
          <p className="text-neutral-600 dark:text-neutral-400">By accessing or using Deep Check (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">2. Description of Service</h2>
          <p className="text-neutral-600 dark:text-neutral-400">Deep Check provides adaptive educational assessments, analytical reports, and personalized learning recommendations for students in Nigerian secondary schools. The Service includes both free and paid tiers.</p>

          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">3. User Accounts</h2>
          <p className="text-neutral-600 dark:text-neutral-400">You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during registration. Accounts found to be fraudulent may be terminated.</p>

          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">4. Payments & Refunds</h2>
          <p className="text-neutral-600 dark:text-neutral-400">Paid services (Deep Reports, Parent Bundles, School Licenses) are processed securely via Paystack. Refunds are available within 7 days of purchase if no assessment has been taken. School term licenses are non-refundable after 14 days.</p>

          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">5. Intellectual Property</h2>
          <p className="text-neutral-600 dark:text-neutral-400">All content, questions, algorithms, and reports generated by Deep Check are the intellectual property of Deep Check. Users may not reproduce, distribute, or create derivative works without permission.</p>

          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">6. Limitation of Liability</h2>
          <p className="text-neutral-600 dark:text-neutral-400">Deep Check provides educational insights and recommendations. We do not guarantee specific academic outcomes. The Service is provided &quot;as is&quot; without warranties of any kind.</p>

          <h2 className="text-xl font-bold text-neutral-900 dark:text-white">7. Contact</h2>
          <p className="text-neutral-600 dark:text-neutral-400">For questions about these terms, contact legal@deepcheck.app.</p>
        </section>
      </div>
    </main>
  );
}
